//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveWare_BurnInInstruments.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolveWare_BurnInInstruments.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by fd (dg) --&gt;
        ///&lt;SMU3133Config xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&gt;&quot;&gt;
        ///	&lt;CardNo&gt;0&lt;/CardNo&gt;
        ///	&lt;PD1_aiCh&gt;1&lt;/PD1_aiCh&gt;
        ///	&lt;PD2_aiCh&gt;1&lt;/PD2_aiCh&gt;
        ///	&lt;MPD1_aiCh&gt;2&lt;/MPD1_aiCh&gt;
        ///	&lt;MPD2_aiCh&gt;3&lt;/MPD2_aiCh&gt;
        ///	&lt;TEC1_aiCh&gt;4&lt;/TEC1_aiCh&gt;
        ///	&lt;TEC2_aiCh&gt;5&lt;/TEC2_aiCh&gt;
        ///	&lt;NTC1_aiCh&gt;6&lt;/NTC1_aiCh&gt;
        ///	&lt;NTC2_aiCh&gt;7&lt;/NTC2_aiCh&gt;
        ///	&lt;PD1_Range_doCh_1&gt;4&lt;/PD1_Range_doCh_1&gt;
        ///	&lt;PD1_Ran [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lxsmuconfig {
            get {
                return ResourceManager.GetString("lxsmuconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by abc (123) --&gt;
        ///&lt;SMUConfiguration xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;DeviceID&gt;1&lt;/DeviceID&gt;
        ///	&lt;!--LD Curr Source:  0.2A = 5V, K=0.04, B=0--&gt;
        ///	&lt;LD_Current_Drive_Channel&gt;0&lt;/LD_Current_Drive_Channel&gt;
        ///	&lt;LD_Current_Source_Range&gt;0.2&lt;/LD_Current_Source_Range&gt;
        ///	&lt;LD_Current_Source_K&gt;0.04&lt;/LD_Current_Source_K&gt;
        ///	&lt;LD_Current_Source_B&gt;0&lt;/LD_Current_Sourc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string smuconfig {
            get {
                return ResourceManager.GetString("smuconfig", resourceCulture);
            }
        }
    }
}
